#!/bin/bash

POSTGRES_PASSWORD=$(sudo microk8s kubectl get secrets postgres -o jsonpath='{.data.postgresql-password}' | base64 -d)

expected=$(cat <<'EOF'  
$(cat table.txt | sed 's/$/\\n/g')
EOF
)

actual=$(sudo microk8s kubectl exec -i postgres-0 -- psql -h localhost -U postgres -d elma365 -W <<< $POSTGRES_PASSWORD -c "\dt+ *.*" 2>&1)

diff -q <(echo "$expected") - <<< "$actual" > /dev/null
DIFF_STATUS=$?

if [ $DIFF_STATUS -eq 0 ]; then
  echo "Все таблицы созданы"
else
  echo "Не все таблицы созданы"
fi
